# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sparklingNumerology' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewNumerology
pod 'Pastel'
pod 'ProgressHUD'
pod 'ChameleonFramework/Swift'
pod 'RealmSwift'
pod 'SwipeCellKit'
#pod "ReverseExtension"

end